services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: {{ cookiecutter.project_slug }}-app
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - 8080:8080
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    working_dir: /app 